In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
os.listdir('../data/raw')

['spotify-tracks-dataset.csv']

In [3]:
df =pd.read_csv('../data/raw/spotify-tracks-dataset.csv')

In [4]:
df.shape

(114000, 22)

In [5]:
df.sample(4)

,Unnamed: 0.1,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
87491,87491,87491,4GYgRE5xx0GrBOiUdz6HTq,Leoni,Leoni - Ao Vivo,Alice (Não Me Escreva Aquela Carta de Amor) / ...,45,201613,False,0.567,...,-8.201,0,0.0397,0.805000,0.000,0.881,0.843,80.557,4,r-n-b
82453,82453,82453,59B5CBl2vFYsZogVmCGf0L,Falconshield;FrivolousShara,PICK YOUR POISON,PICK YOUR POISON,40,187494,False,0.653,...,-12.702,0,0.0794,0.107000,0.000,0.219,0.308,144.830,4,power-pop
59965,59965,59965,3j78wdlIk5WfnfddP2qySc,Nima A.M.,The Frequency,Love in Fall,0,353000,False,0.526,...,-7.513,1,0.0280,0.000317,0.826,0.105,0.254,120.019,4,iranian
65840,65840,65840,5joNJn9LUvYcamWwa2iYCL,OH MY GIRL,NONSTOP,Nonstop,62,202760,False,0.753,...,-2.591,1,0.0517,0.171000,0.000,0.367,0.825,123.983,4,k-pop

In [6]:
df.drop(['Unnamed: 0.1','Unnamed: 0', 'track_id' ], axis=1, inplace= True)

In [7]:
df.sample(2)

,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
101114,Traditional;Andrea Bocelli,Classical Christmas,Angels We Have Heard On High,0,233453,False,0.158,0.379,7,-5.842,1,0.0303,0.8360,0.000763,0.113,0.178,89.917,1,sleep
17833,DEADLIFE,Bionic Chrysalis,For You,16,353061,False,0.580,0.569,10,-6.291,0,0.0760,0.0171,0.067200,0.089,0.358,122.416,4,club

In [8]:
df.isna().sum()

artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [9]:
df["artists"].isna().sum()

np.int64(1)

In [10]:
df[ df["artists"].isna()]

,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,NaN,NaN,NaN,0,0,False,0.501,0.583,7,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

In [11]:
df[  df["album_name"].isna()]

,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,NaN,NaN,NaN,0,0,False,0.501,0.583,7,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

In [12]:
df[  df["track_name"].isna()]

,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,NaN,NaN,NaN,0,0,False,0.501,0.583,7,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

In [13]:
df = df.drop(65900).reset_index(drop=True)

In [14]:
df.isna().sum()

artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [15]:
df.shape

(113999, 19)

In [16]:
df.duplicated().sum()

np.int64(577)

In [17]:
#df.drop_duplicates(keep='last', inplace=True)

In [18]:
df.duplicated().sum()

np.int64(577)

In [19]:
df[ df.duplicated()]

,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
1925,Buena Onda Reggae Club,Disco 2,Song for Rollins,16,219346,False,0.841,0.577,0,-7.544,1,0.0438,0.238000,0.860000,0.0571,0.843,90.522,4,afrobeat
2046,The Killers;Ryan Pardey,Alternative Christmas 2022,Don't Shoot Me Santa,0,245106,False,0.588,0.847,8,-4.164,1,0.0705,0.060100,0.000000,0.3070,0.662,120.041,4,alt-rock
2085,The Smashing Pumpkins,Alternative Christmas 2022,Christmastime,0,196723,False,0.165,0.434,0,-8.163,1,0.0288,0.316000,0.171000,0.2130,0.186,77.983,3,alt-rock
2094,Weezer,Alternative Christmas 2022,We Wish You A Merry Christmas,0,84973,False,0.387,0.786,11,-4.127,1,0.0436,0.019500,0.000000,0.1230,0.462,149.806,3,alt-rock
2155,Red Hot Chili Peppers,Stadium Arcadium,Snow (Hey Oh),80,334666,False,0.427,0.900,11,-3.674,1,0.0499,0.116000,0.000017,0.1190,0.599,104.655,4,alt-rock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111361,Faithless,Faithless 2.0,Tarantula,21,398152,False,0.622,0.816,6,-11.095,0,0.0483,0.009590,0.578000,0.0991,0.427,136.007,4,trip-hop
111979,Morcheeba,Parts of the Process,Undress Me Now,17,203773,False,0.576,0.352,7,-10.773,0,0.0268,0.700000,0.270000,0.1600,0.360,95.484,4,trip-hop
112967,Acil Servis,Küçük Adam,Bebek,38,319933,False,0.486,0.485,5,-12.391,0,0.0331,0.004460,0.000017,0.3690,0.353,120.095,4,turkish
113344,Matt Redman,Sing Like Never Before: The Essential Collection,Our God - New Recording,34,265373,False,0.487,0.895,11,-5.061,1,0.0413,0.000183,0.000000,0.3590,0.384,105.021,4,world-music
113881,Bryan & Katie Torwalt,I've Got Good News (Live) [Deluxe],Good News - Live,23,266632,False,0.473,0.474,6,-9.175,1,0.0558,0.395000,0.000000,0.1630,0.251,140.746,4,world-music

# Extract KPIs as :
- No. of tracks
- No. of artists
- No. of albums
- Avg song duration is minutes
- No. of genres

In [20]:
df.sample(1)

,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
95603,Jorge Leo & Atrato River,Desbordante,Amor Tormentoso,29,252107,False,0.688,0.78,4,-10.831,0,0.0517,0.273,0.00208,0.0544,0.653,177.066,4,salsa

In [21]:
No_of_tracks = df.drop_duplicates(subset=["track_name"], keep='last').value_counts().sum()

No_of_tracks

np.int64(73608)

In [22]:
No_of_artists = df.drop_duplicates(subset=['artists'], keep='first').value_counts().sum()
No_of_artists

np.int64(31437)

In [23]:
No_of_albums = df.drop_duplicates(subset=["album_name"], keep='last').value_counts().sum()

No_of_albums

np.int64(46589)

In [24]:
df["duration_ms"].mean()/1000

np.float64(228.0311533873104)

In [25]:
Avg_song_duration_is_minutes = round(df["duration_ms"].mean() / 1000/60, 2)

Avg_song_duration_is_minutes

np.float64(3.8)

In [26]:
No_of_genres = df.drop_duplicates( subset=["track_genre"], keep="last").value_counts().sum()

No_of_genres

np.int64(114)

# Extract KPIs as :

In [28]:
print(f'No. of tracks: {No_of_tracks}')
print(f'No. of artists: {No_of_artists}')
print(f'No. of albums: {No_of_albums}')
print(f'Avg song duration is minutes: {Avg_song_duration_is_minutes}')
print(f'No. of genres: {No_of_genres}')

No. of tracks: 73608
No. of artists: 31437
No. of albums: 46589
Avg song duration is minutes: 3.8
No. of genres: 114

In [ ]:
df.to_csv('../data/cleaned_data/cleaned_spotifiy_dataset.csv')